import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import {Nav, Navbarr} from '@/components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SnipRead',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={` bg-black ${inter.className}`}>
      <Nav />
      {/* <Navbarr/> */}
        {children}
      </body>
    </html>
  )
}
